name: Merge branch workflow

on:
  push:
    branches:
      - 'release**'
    tags:
      - 'v**'

jobs:
  build:
    name: merge branch
    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Merge to uat branch
#        uses: devmasx/merge-branch@v1.1.0
#        with:
#          type: now
#          target_branch: 'master'
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "master"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "wei,worker"                         # Comma-separated list (no spaces)
          pr_assignee: "wei,worker"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                       # Milestone name
          pr_draft: true                                    # Creates pull request as draft
          github_token: ${{ secrets.GITHUB_TOKEN }}



