name: Regression buid workflow

on:
  push:
    branch:
      - 'release/*'

jobs:
  build:
    name: Make release apk and upload it to Drive , Slack & send Mail to organization about regression build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt


      - name: Generate Change logs
        id: changelogs
        working-directory: .github/workflows/
        #        run: echo "::set-output name=changelog::$(echo python release_mail_generator.py ${{ secrets.GITHUB_TOKEN }}  v2.21)"
        run: python release_mail_generator.py ${{ secrets.GITHUB_TOKEN }}  v2.21



      - name: Getting build no & tag name
        uses: jungwinter/split@v1
        id: tag name
        with:
          msg: merchant-418-2.20.1.apk
          seperator: '-'

      - name: Echo build info
        run: |
          echo ${{ steps.split.outputs._0 }}
          echo build no ${{ steps.split.outputs._1 }}
          echo ${{ steps.split.outputs._3 }}

      - name: Splitting for tag name
        uses: jungwinter/split@v1
        id: split_tag
        with:
          msg: ${{ steps.split.outputs._3 }}
          seperator: '.'

      - name: Tag name
        run: |
          echo v${{ steps.split.outputs._0 }}

      - name: Extract branch name
        id: branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"


      - name: Replace string
        id: replace_string
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-text: ${{ steps.branch_name.outputs.branch }}
          release: merchant


      - name: Echo
        run: |
          echo ${{ steps.branch_name.outputs.branch }}
          echo ${{ steps.replace_string.outputs.result }}


      - name: Setup JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: bash ./gradlew assembleRelease


      - name: Getting generated APK name
        id: list_files
        working-directory: app/build/outputs/apk/release/
        run: echo "::set-output name=apk_name::$(echo *.apk)"


      - name: Echo apk name
        run: |
          echo ${{ steps.list_files.outputs.apk_name }}

      - name: Upload APK to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: app/build/outputs/apk/release/${{steps.list_files.outputs.apk_name}}
          upload-to: /release_apks


      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER_NAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Android Regression CI/CD Test
          body: ${{ steps.changelogs.outputs.changelog }}
          to: karthik@okcredit.in
          from: ${{ secrets.GMAIL_USER_NAME }}
          content_type: text/html
          #attachments: app/build/outputs/apk/prodFlavour/artifacts/newYorlTimes


      - name: Upload APK to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_SECRETS }}
          initial_comment: ${{ steps.changelogs.outputs.changelog }}
          path: app/build/outputs/apk/release/${{steps.list_files.outputs.apk_name}}
          channel: android_ci_cd_test


