name: Regression buid workflow

on:
  push:
    branches:
      - 'release*'
    tags-ignore:
      - v*

jobs:
  build:
    if: github.event.label.name == 'regression'
    name: Make release apk and upload it to Drive , Slack & send Mail to organization about regression build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip
        run: |
         python -m pip install --upgrade pip
         pip install -r .github/workflows/requirements.txt

      - name: Make Gradle executable
         run: chmod +x ./gradlew

      - name: Build QA APK
        run: bash ./gradlew assembleDebug


      - name: Upload APK to Google Drive
        uses: satackey/action-google-drive@v1
        with:
            skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
            upload-from: app/build/outputs/apk/debug/app-debug.apk
            upload-to: /TEMP1/v2.22.0/PLAY_STORE/QA